name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Download bats
      run: |
        if [[ ! -e deps/bats_v0.4.0.tar.gz ]];
          then
            mkdir -p deps
            curl -sSL -o deps/bats_v0.4.0.tar.gz \
            https://github.com/sstephenson/bats/archive/v0.4.0.tar.gz
            tar -xf deps/bats_v0.4.0.tar.gz
        fi
    - name: Install Docker Deps
      run: |
        sudo apt-get install \
          apt-transport-https \
          ca-certificates \
          curl \
          gnupg-agent \
          software-properties-common
    - name: Add Docker GPG Key
      run: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - name: Add Docker CE Repo
      run: |
        sudo add-apt-repository \
        "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) \
        stable"
    - name: Install Docker CE
      run: sudo apt-get install docker-ce docker-ce-cli containerd.io
    - name: Install manifest tool
      run: |
        if [[ ! -e deps/manifest-tool-linux-amd64 ]];
            then
              mkdir -p deps
              curl -sSL -o deps/manifest-tool-linux-amd64 \
              https://github.com/estesp/manifest-tool/releases/download/v0.6.0/manifest-tool-linux-amd64
        fi
        chmod +x deps/manifest-tool-linux-amd64
